\section{Abridged version}
This document will introduce two concepts,
bindables and resumable exceptions,
and will try to show that they can do surprising things.

\subsection{Bindables}
Roughly, a bindable anything which supports an
interface of two functions $bind$ and $new$.
\begin{align}
    bind &:: B\ x \rightarrow (x \rightarrow List\ y) \rightarrow B\ y\\
    new &:: x \rightarrow B\ x
\end{align}
The way to read is that $::$ means "is of type",
the bind function takes two things,
firstly $B\ x$, which means any bindable of underlying type $x$
where $x$ can be any type you want.
Then it takes $(x \rightarrow B\ y)$ which
is a function taking type $x$,
to the type $B\ y$ which a bindable of type $y$
where $y$ is any type
(and potentially but not necessarily type $x$).
Having been given those two things,
$bind$ returns a bindable of type $y$.
You could think of $bind$ as a sequencer between bindables.

The $new$ function takes any value and
constructs a bindable on top of that value.
Bindables can be built on top of any value,
even a bindable of the same type
or a completely different bindable entirely
(which is of course built on some other value).

Let's give a concrete example,
the easiest and most ubiquitous example of a bindable are lists.
\begin{align}
    bind &:: List\ x \rightarrow (x \rightarrow List\ y) \rightarrow List\ y\\
    new &:: x \rightarrow List\ x
\end{align}
Now implementing $new$ is pretty easy.
\begin{verbatim}
    //Note we use 'unit' as return is a keyword
    const new = x => [x];
    console.log(new(1));
    // === Array [1]
\end{verbatim}

To define bind we gotta define an auxiliary function called join first,
it takes a list of lists and returns a list.
It basically just flattens the list given,
appending each list to the one before it.

\begin{verbatim}
    const arr2 = [[1, 2], [3, 4]];
    const append = (onto, val) => onto.concat(val);
    const join = x => x.reduce(append, []);
    console.log(join(arr2));
    // === Array [1, 2, 3, 4]
\end{verbatim}
Once we have done that, defining bind is pretty simple
\begin{verbatim}
    const bind = (x, f) => join(x.map(f));
    const sqrButKeep = x => [x, x*x];
    console.log(bind([2, -9, 49], sqrButKeep));
    // === Array [2, 4, -9, 81, 49, 2401]
\end{verbatim}

So these examples illustrate what the functions do,
but they are not terribly useful.
From these simple pieces we can create much
more complicated things.
For example, using bindables we can get get rid of null-pointer exceptions.
And exceptions in general!
They cleverly short circuit computations like \texttt{\&\&}.
They can be used to create state out of immutability.
They can even replace the most common Go idiom:
\begin{verbatim}
    result, err := myFunction()
    if err != nil {
        return nil, err
    }
\end{verbatim}

Let's explore removing exceptions.
Since Go already does not have exceptions
we can start with that and show how to improve it even further.
A result is either an error (of type $y$),
or a successful computation (of type $x$).
Having defined that we can create result bindable.
Here is what bind for result might look like in JS.
\begin{verbatim}
    let bind = (result, fn) => {
        if (result.isErr()) {
            return result;
        } else {
            return fn(result);
        }
    }
\end{verbatim}
Now given a sequence of Go-like computations,
any of which may fail,
\begin{verbatim}
    name, err := dbCall(init)
    if err != nil {
        return nil, err
    }
    ipAddr, err := tableLookUp(name)
    if err != nil {
        return nil, err
    }
    geoLoc, err := getLoc(name, ipAddr)
    if err != nil {
        return nil, err
    }
    return create_profile(name, geoLoc)
\end{verbatim}
We can rephrase our code using bind,
assuming that bind is a method of result type objects.
First we call $new$ on \texttt{init} so we can begin our
sequence.
\begin{verbatim}
    new(init).bind(fun init ->
        dbCall(init).bind(fun name ->
            tableLookUp(name).bind(fun ipAddr ->
                getLoc(name, ipAddr).bind(fun geoLoc ->
                    return create_profile(name, geoLoc)
                )
            )
        )
    )
\end{verbatim}
As it turns out we ended up with a pyramid of doom and not an improvement.
But using code (AST) processing tools we can get something much simpler,
\texttt{letbind} simply rewrites the code below into the code above.
\begin{verbatim}
    letbind name := dbCall(init)
    letbind ipAd := tableLookUp(name)
    letbind geoL := getLoc(name, ipAddr)
    return create_profile(name, geoLoc)
\end{verbatim}
This code is much simpler and allows us just as much
safety and expressiveness as the Go code.

\subsection{Resumable Exceptions}
A resumable exception is an extension normal exceptions
and exceptions handlers, except we get a continuation to play with.
We can implement async/await using resumable exceptions.
Or concurrency. Or as we mentioned, nearly
anything bindables can do.
Proving that resumable exceptions can replace normal
exceptions seems rather tautological,
as such we will explore stateful computation.

We firstly need a wrapper function which will
take an initial state and will play through
the state as it changes. At no point
do we mutate the state, we just pass an updated
state whenever it is requested.
\begin{verbatim}
function runState(statefulFn, initState) {
    let runState = () => try {
        statefulFn();
    } with {
      { type: "Value", value } => (state => (state, value)),
      { type: "Get", cont } => (curState =>
          continue(cont, curState)(curState))
      { type: "Put",   value: newState, cont } => (
          state => continue(cont)(newState))
    }
    runState()(initState);
}
\end{verbatim}
What happens here is that every time we catch something we build up a function,
for example \texttt{(state => (state, value))} means I will return
you a function which when given a state will give you back the value
and the state.
Similarly \texttt{(state => continue(cont)(newState))}
says I will continue where I was before and whatever that returns
is applied to the newState I was just told to use.
Eventually the initial state is passed in
and the entire function we built up evaluates.
This makes it seem like we have mutable state
where actually we just have different values
being passed between functions.

The \texttt{perform} function throws an effect/exception
which we catch and deal with according to it's type.
Each time it also gives our handler as continuation
so we can get back where we were previously.

Finally we can play through the computation
using our wrapper function,
some computation to run,
and an initial state.
\begin{verbatim}
let incrTwice = () => {
  perform("Set", (perform("Get") + 1));
  perform("Set", (perform("Get") + 1));
  return perform("Get");
}

runState(incrTwice, 0) // === 2
\end{verbatim}
